### ISSUE TITLE
Older llvm17 release gone and llvm18 release have libstdc++ link problem

### ISSUE THREAD

**Issue by jackalcooper** [makslevental/mlir-wheels#23]
## LLVM 17
- I used to pin `mlir==17.0.0+ffbca7e9` and it is absent in the index page.
- Newer llvm17 ones all have same commit 35ca6498, for instance `17.0.0.2023082722+35ca6498`

## LLVM 18
- library fails to build when linking all dependencies, and reports failing to find libstdc++ symbols
```
/usr/bin/ld: /opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/mlir/lib/libLLVMSupport.a(ThreadPool.cpp.o): in function `llvm::ThreadPool::isWorkerThread() const':
ThreadPool.cpp:(.text._ZNK4llvm10ThreadPool14isWorkerThreadEv+0xb3): undefined reference to `std::__glibcxx_assert_fail(char const*, int, char const*, char const*)'
/usr/bin/ld: ThreadPool.cpp:(.text._ZNK4llvm10ThreadPool14isWorkerThreadEv+0xdb): undefined reference to `std::__glibcxx_assert_fail(char const*, int, char const*, char const*)'
/usr/bin/ld: /opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/mlir/lib/libLLVMSupport.a(ThreadPool.cpp.o):ThreadPool.cpp:(.text._ZN4llvm10ThreadPoolD2Ev+0x2d7): more undefined references to `std::__glibcxx_assert_fail(char const*, int, char const*, char const*)' follow
/usr/bin/ld: /opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/mlir/lib/libMLIRAsyncTransforms.a(AsyncToAsyncRuntime.cpp.o): in function `mlir::RewritePatternSet& mlir::RewritePatternSet::add<(anonymous namespace)::AwaitTokenOpLowering, (anonymous namespace)::AwaitValueOpLowering, (anonymous namespace)::AwaitAllOpLowering, mlir::MLIRContext*&, std::shared_ptr<llvm::DenseMap<mlir::func::FuncOp, (anonymous namespace)::CoroMachinery, llvm::DenseMapInfo<mlir::func::FuncOp, void>, llvm::detail::DenseMapPair<mlir::func::FuncOp, (anonymous namespace)::CoroMachinery> > >&, bool, void>(mlir::MLIRContext*&, std::shared_ptr<llvm::DenseMap<mlir::func::FuncOp, (anonymous namespace)::CoroMachinery, llvm::DenseMapInfo<mlir::func::FuncOp, void>, llvm::detail::DenseMapPair<mlir::func::FuncOp, (anonymous namespace)::CoroMachinery> > >&, bool&&) [clone .isra.0]':
AsyncToAsyncRuntime.cpp:
```
- a full log: https://github.com/beaver-lodge/beaver/actions/runs/6753815040/job/18360684674

**Comment by makslevental** [comment]
> I used to pin mlir==17.0.0+ffbca7e9 and it is absent in the index page.

I recently flushed old commits. Sorry. I've kicked off a build for that commit for you: https://github.com/makslevental/mlir-wheels/actions/runs/6755591812.

> library fails to build when linking all dependencies, and reports failing to find libstdc++ symbols

You're linking against the wrong glibc - all these wheels are built inside manylinux_2_28, which has a fixed glibc and I guess by extension libstdc++. I see you're using Ubuntu 20 runners - they should work as I have other downstream projects that similarly use Ubuntu 20 runners. In addition I see exception pointers missing but I can't tell in which direction - these wheels are built with RTTI but not with exceptions. Can you link me to your exact CMake? Sorry I'm not familiar with elixir so I couldn't find it.

**Comment by jackalcooper** [comment]
> I've kicked off a build
Thank you! 

> Can you link me to your exact CMake? 
root cmake: https://github.com/beaver-lodge/beaver/blob/main/native/mlir-c/CMakeLists.txt
CAPI aggregate cmake: https://github.com/beaver-lodge/beaver/blob/main/native/mlir-c/aggregate/MLIR/CMakeLists.txt
CAPI library cmake: https://github.com/beaver-lodge/beaver/blob/main/native/mlir-c/lib/CAPI/CMakeLists.txt

**Comment by makslevental** [comment]
@jackalcooper looking again the logs (because I didn't see anything suspcious in the CMakes), I see

```
ThreadPool.cpp:(.text._ZN4llvm10ThreadPool4growEi+0x270): undefined reference to `std::__glibcxx_assert_fail(char const*, int, char const*, char const*)'
```

In particular the `__glibcxx_assert_fail`, which I believe is because I compile the wheels with `-DLLVM_ENABLE_ASSERTIONS=ON`. I'm not sure where you're exactly calling CMake but I didn't see assertions enabled in the CMakes themselves. For reference, here's the complete set of flags I pass to CMake:

https://github.com/makslevental/mlir-wheels/blob/main/setup.py#L99-L102

**Comment by jackalcooper** [comment]
>  I see you're using Ubuntu 20 runners - they should work as I have other downstream projects that similarly use Ubuntu 20 runners. 

I added them to check if it is ubuntu's problem. I used to build with `ubuntu-latest`, and now it fails on both `ubuntu-20.04` and `ubuntu-latest`

## Some other findings
- After using your kindly built wheel `mlir==17.0.0.2023110415+ffbca7e9`, it has another link error.
https://github.com/beaver-lodge/beaver/actions/runs/6758106298/job/18369387603
Explicitly linking the library where the method is implemented doesn't help. diff: https://github.com/beaver-lodge/beaver/commit/85d3137dda041b1cff823540b69cb4be4b08433e
- Also I found a discussion about `LLVM_ENABLE_ASSERTIONS` on Phabricator: https://reviews.llvm.org/D142279
- Any changes you might think of could affect linkage since adding date to the version?

**Comment by makslevental** [comment]
@jackalcooper 

I believe this means you are building with the old ABI:

```
/home/runner/work/beaver/beaver/native/mlir-c/lib/CAPI/Beaver.cpp:31: undefined reference to `mlir::FrozenRewritePatternSet::FrozenRewritePatternSet(mlir::RewritePatternSet&&, llvm::ArrayRef<std::string>, llvm::ArrayRef<std::string>)'
```

Searching in your repo I see

https://github.com/beaver-lodge/beaver/blob/main/native/mlir-c/lib/CAPI/Beaver.cpp#L2. Not sure why you're setting that there (or why you're setting it at all?) but you can try setting to 1.

**Comment by jackalcooper** [comment]
> Not sure why you're setting that there (or why you're setting it at all?) 

I think I added it so it can find the symbol, before I started using the pre-built wheels.

> but you can try setting to 1.

after setting it to 1 or deleting the line, the build succeeds on `ubuntu-latest` and fails on `ubuntu-20.04`
https://github.com/beaver-lodge/beaver/actions/runs/6759502404/job/18372217104

**Comment by makslevental** [comment]
@jackalcooper yea so I think this is about "correct"; you need gcc-12 (see [manylinux_2_28](https://github.com/pypa/manylinux#manylinux_2_28-almalinux-8-based)). What's interesting/weird/confusing is that I do have ubuntu-20 native builds going in various places _but only for aarch64_ which I believe works because for the aarch64 wheels (here) I statically linked libstdc++ (see [here](https://github.com/makslevental/mlir-wheels/actions/runs/6758403037/job/18369999505#step:7:132)). I guess I could statically link for all wheels (not just aarch64) but I'm not sure I want to do that? Maybe I do? I need to think about the implications.

**Comment by jackalcooper** [comment]
> I statically linked libstdc++ (see [here](https://github.com/makslevental/mlir-wheels/actions/runs/6758403037/job/18369999505#step:7:132)).

I found that if I add `-DCMAKE_CXX_FLAGS="-static-libstdc++"`, the `ubuntu-latest` build used to work also fails and it still fails on 20.04
diff https://github.com/beaver-lodge/beaver/commit/7bc8c7fee358c7f1474a08ce7c4c27145a97e7d6

**Comment by makslevental** [comment]
The only thing I can recommend is to static link both DCMAKE_CXX_FLAGS=-static-libgcc -static-libstdc++

**Comment by jackalcooper** [comment]
> The only thing I can recommend is to static link both DCMAKE_CXX_FLAGS=-static-libgcc -static-libstdc++

same😿. Could you point me to a downstream project using the wheels?

**Comment by makslevental** [comment]
@jackalcooper Here you go https://github.com/Xilinx/mlir-aie/actions/runs/6759229921/workflow#L149-L159 with the actual scripts being here https://github.com/Xilinx/mlir-aie/tree/wheels2.

**Comment by makslevental** [comment]
@jackalcooper so how did you fix?

**Comment by jackalcooper** [comment]
> @jackalcooper so how did you fix?

i stopped using Ubuntu 20.04, considering it doesn't support gcc12 if not building it from source
