### ISSUE TITLE
add mlir-opt and friends from the wheel to path

### ISSUE THREAD

**Issue by superlopuh** [makslevental/mlir-wheels#29]
Would it be possible to make the binaries available through the CLI when pip-installing?

**Comment by makslevental** [comment]
> Would it be possible to make the binaries available through the CLI when pip-installing?

Which wheel? `mlir` or `mlir-python-bindings`?

**Comment by superlopuh** [comment]
Either, I only tried with `mlir`, should I try with `mlir-python-bindings`?

**Comment by makslevental** [comment]
@superlopuh which friends exactly? i.e., other than `-opt` and `-translate`...
