### ISSUE TITLE
LLVM 15

### ISSUE THREAD

**Issue by kaarmu** [makslevental/mlir-wheels#30]
Hello,

Nice to see prebuilt binaries for mlir! Is it possible for you to build for LLVM 15.0.0, i.e. https://github.com/llvm/llvm-project/commit/4ba6a9c9f65bbc8bd06e3652cb20fd4dfc846137?

**Comment by makslevental** [comment]
https://github.com/makslevental/mlir-wheels/actions/runs/8027417982/job/21931347593

Note the builds are "garbage cleaned" (removed) after 30 days.

**Comment by kaarmu** [comment]
Thanks!

**Comment by kaarmu** [comment]
Hmm, it seems that the build failed
