### ISSUE TITLE
Question regarding building a wheel locally

### ISSUE THREAD

**Issue by mtsokol** [makslevental/mlir-wheels#60]
Hi @makslevental,

Sorry if this is not the right place to ask but I wanted to ask about your wheel building procedure.

I have a locally build LLVM/MLIR and I'm trying to locally build a Python wheel out of it (following that takes place in the CI in this repo).

Currently I'm building LLVM locally with a command inside the `build` directory:
```
cmake -G Ninja ../llvm \
    -DLLVM_ENABLE_PROJECTS=mlir;llvm;clang;lld \
    -DLLVM_TARGETS_TO_BUILD=Native \
    -DCMAKE_BUILD_TYPE=Release \
    -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
    -DPython3_EXECUTABLE=/home/mtsokol/.conda/envs/llvm-dev/bin/python3 \
    -DLLVM_INSTALL_UTILS=ON
```
And then I install it to `build-install` directory:
```
cmake -DCMAKE_INSTALL_PREFIX=../build-install -P cmake_install.cmake
```
Then after setting `PYTHONPATH` env var I can freely use my build package with my dialect:
```
export PYTHONPATH=/home/mtsokol/llvm-project-main/build-install/python_packages/mlir_core
```
```python
from mlir.dialects import memref, sparse_tensor, linalg
```

---

I would like to make this package a wheel that I can install with `pip`. I followed a `setup.py` file in your `mlir-wheels` repo, drafted my steps as an extension module:
```python
import subprocess
from pathlib import Path

from setuptools import Extension, setup
from setuptools.command.build_ext import build_ext

class CMakeExtension(Extension):
    def __init__(self, name: str, sourcedir: str = "") -> None:
        super().__init__(name, sources=[])

class CMakeBuild(build_ext):
    def build_extension(self, ext: CMakeExtension) -> None:
        install_dir = "/home/mtsokol/llvm-project-main/build-install"

        cmake_args = [
            "-G Ninja",
            "../llvm",
            "-DLLVM_ENABLE_PROJECTS=mlir;llvm;clang;lld",
            "-DLLVM_TARGETS_TO_BUILD=Native",
            "-DCMAKE_BUILD_TYPE=Release",
            "-DMLIR_ENABLE_BINDINGS_PYTHON=ON",
            "-DPython3_EXECUTABLE=/home/mtsokol/.conda/envs/llvm-dev/bin/python3",
            "-DLLVM_INSTALL_UTILS=ON"
        ]

        subprocess.run(
            ["cmake", *cmake_args], cwd=Path.cwd(), check=True,
        )

        subprocess.run(
            ["cmake", "-DCMAKE_INSTALL_PREFIX=../build-install", "-P cmake_install.cmake"],
            cwd=Path.cwd(),
            check=True,
        )

        subprocess.run(
            [
                "find", ".", "-exec", "touch", "-a", "-m", "-t", "197001010000", "{}", ";",
            ],
            cwd=install_dir,
            check=False,
        )


setup(
    name="mlir",
    version="0.0.1",
    ext_modules=[CMakeExtension("mlir_finch_ext")],
    cmdclass={"build_ext": CMakeBuild},
    zip_safe=False,
)
```
But it looks like the wheel that is built with `python3 setup.py bdist_wheel` or `pip wheel .` isn't close to what I need:
```sh
~/llvm-project-main/build$ ls -al dist/
-rw-rw-r--  1 mtsokol mtsokol 1052 Oct 16 11:01 mlir-0.0.1-cp310-cp310-linux_x86_64.whl
```

I see that during wheel building process the `cmake` commands are executed correctly but I think the resulting Python package isn't placed inside `whl` file. In your `setup.py` file I can't find where the build Python package is actually placed in `whl`.
Do you know that I'm missing in my setup? (I'm not familiar with wheel building with extensions yet)

**Comment by mtsokol** [comment]
Ah, I see that `mlir` is separate from `mlir-python-bindings` package in `python_bindings`, but I would have the same question about building `mlir-python-bindings` wheel locally.

**Comment by makslevental** [comment]
The install dir isn't arbitrary - you have to "install" into the location the pip/setuptools expects extension [modules to be](https://github.com/makslevental/mlir-wheels/blob/main/setup.py#L35-L37):

```python
        ext_fullpath = Path.cwd() / self.get_ext_fullpath(ext.name)
        extdir = ext_fullpath.parent.resolve()
        install_dir = extdir / "mlir"
        ...
        cmake_args = [
            ...
            f"-DCMAKE_INSTALL_PREFIX={install_dir}",
            ...
        ]
```

**Comment by mtsokol** [comment]
@makslevental That was exactly what I was missing - thank you!

To give some context I have an MLIR dialect (https://github.com/nullplay/Finch-mlir) that I'm building in-tree (or out-of-tree, monolithic build) with my local LLVM build and then I want to distribute it as a wheel.

Here's a `setup.py` that worked for me: https://gist.github.com/mtsokol/0de993860e7eff7980226703e3ea8df9 (so using install directory relevant to pip solved my problem).

Last thing is that for some reason after installing `whl` file with pip, my Python package is placed under:
```
/home/mtsokol/.conda/envs/test-llvm-finch/lib/python3.10/site-packages/python_packages/finch/mlir_finch
```
instead of:
```
/home/mtsokol/.conda/envs/test-llvm-finch/lib/python3.10/site-packages/mlir_finch
```
where `test-llvm-finch` is my conda env. After moving `mlir_finch` up two directories package can be imported and works as expected. Did you experience something similar?

(Installing MLIR/LLVM without my dialect yields same result - the package is under `.../site-packages/python_packages/mlir_core/mlir` rather than `.../site-packages/mlir`)

**Comment by mtsokol** [comment]
Ok, it turns out that `CMakeLists.txt` in `standalone/python` had these paths hardcoded: https://github.com/llvm/llvm-project/blob/2b6b7f664d9c93877ce6678820255fc006d56b54/mlir/examples/standalone/python/CMakeLists.txt#L38
Removing `python_package/standalone` part fixed my issue and now importing works as expected.

**Comment by makslevental** [comment]
mpt sir

> Ok, it turns out that `CMakeLists.txt` in `standalone/python` had these paths hardcoded: https://github.com/llvm/llvm-project/blob/2b6b7f664d9c93877ce6678820255fc006d56b54/mlir/examples/standalone/python/CMakeLists.txt#L38 Removing `python_package/standalone` part fixed my issue and now importing works as expected.

I guess you had copied that CMake for your own bindings? And carried over the hardcoding?

**Comment by mtsokol** [comment]
That's right, we took the whole standalone example for our dialect's initial setup.

**Comment by makslevental** [comment]
> That's right, we took the whole standalone example for our dialect's initial setup.

Can you submit a PR to fix upstream or open an issue upstream and assign to me so I can fix it.

**Comment by makslevental** [comment]
Sorry - despite your great/thorough descriptions I guess I misunderstood what the issue was. I thought you meant `INSTALL_DESTINATION python_packages/standalone/mlir_standalone/_mlir_libs` was somehow placing the directory outside of the install tree because it didn't have a `${CMAKE_BINARY_DIR}` parameterization (or something like that). Reading your second response, which jogged my memory on how `INSTALL_DESTINATION` works, I agree we should leave it alone and that it was essentially user error on your part - `INSTALL_DESTINATION` is [documented](https://github.com/llvm/llvm-project/blob/main/mlir/cmake/modules/AddMLIRPython.cmake#L460-L461) but of course finding CMake doc strings is a pain in the ass :)
